cozy/cozy-pass-web

src/app/vault/add-edit.component.html
src/app/vault/groupings.component.html

Folders support is disabled until sharing feature is implemented
TOTP support is disabled until it is implemented by the Stack
Notes support is disabled to prevent confusion with Cozy Notes

Feat/hide folders, TOTP and notes

---

manifest.webapp

App manifest was not set correctly

fix: revert to old application name

---

src/app/vault/ciphers.component.ts

Old code was used because `deleteManyWithServer`, `softDeleteManyWithServer` and `restoreManyWithServer` were not implemented by cozy.
They are now supported and used.

fix: multiple cipher deletion and restoration now use `many` methods

---

src/cozy/react/locales/en.json
src/cozy/react/locales/fr.json

Old text was confusing as Install page is already part of Cozy Pass so `Open Cozy Pass` was a non-sens

fix: reword `Open Cozy Pass` to `Open my passwords`

---

src/locales/es/messages.json

Spanish option is available in Cozy settings so translation entries
should exist in the spanish file. They are filled in english for now
in order to prevent "blank" labels but they should be translated later.

fix: add spanish missing entries using english texts

---

src/cozy/wrappers/angular-wrapper.component.ts
src/cozy/wrappers/button-extension/button-extension.component.ts
src/cozy/wrappers/button-extension/button-extension.jsx
src/cozy/wrappers/import-page/import-page.component.ts
src/cozy/wrappers/import-page/import-page.jsx
src/cozy/wrappers/installation-page/installation-page.component.ts
src/cozy/wrappers/installation-page/installation-page.jsx
src/cozy/wrappers/react-wrapper.jsx

`ReactWrapper` props have been merged in a single `reactWrapperProps`
prop
This makes easier to instantiate needed props from
`angular-wrapper.component` and all inherited components. Therefore
those will be easier to maintain
Also `ReactWrapper` prop-types are now more complete

feat: rework ReactWrapper props

---

src/app/vault/ciphers.component.html
src/scss/cozy.scss

feat: replace `cozy-cloud` icon by `share` icon on shared ciphers

---

package-lock.json
package.json

`cozy-client` has been updated to `24.6.1` to retrieve a fix on how
sharing rules are generated for organization from cozy/cozy-client#1028

feat: bump `cozy-client` version to 24.6.1

---

src/cozy/wrappers/icon-sprite/icon-sprite.component.ts

Change the way Sprit are imported to reflect latest changes from
cozy/cozy-ui@478e9d258804b88f13fb6bae3b0cc6626b8f53e6
___
⚠️ this PR cannot be merged yet, cozy-ui need to be upgraded to 52.0.1 first (will be done with https://github.com/cozy/cozy-pass-web/pull/51)

fix: use correct Sprit import

---

CHANGELOG.md
src/app/app.module.ts
src/app/services.module.ts
src/app/vault/groupings.component.html
src/app/vault/groupings.component.ts
src/cozy/react/locales/en.json
src/cozy/react/locales/fr.json
src/cozy/wrappers/confirm-your-identity-dialog/confirm-your-identity-dialog.component.ts
src/cozy/wrappers/confirm-your-identity-dialog/confirm-your-identity-dialog.jsx
src/cozy/wrappers/confirm-your-identity-dialog/styles.css
src/scss/cozy.scss
src/services/user.service.ts

~~⚠️ this PR must not be merged on `feat/auto_accept_trusted_users` but on `master`. The target branch will be edited after `feat/auto_accept_trusted_users` merge~~
~~⚠️ this PR should not be merged before `feat/auto_accept_trusted_users`~~
____
In be19101f7c286e9dfc1c1a18babded26ea62a754 we chose to hide
organizations with no encryption key to prevent encryption error
messages
Those organizations are shared organizations that are not confirmed by
the sharing owner
This commit display them again in the navbar but with a greyed style
When clicking on those organizations then we display a dialog to
explain to the user that they need to confirm their identity to
finalize the sharing

feat: display org with no key in navbar

---

CHANGELOG.md
src/app/vault/ciphers.component.html
src/app/vault/ciphers.component.ts
src/app/vault/vault.component.ts

~~⚠️ this PR must not be merged on `feat/readonly` but on `master`. The target branch will be edited after `feat/readonly` merge~~
~~⚠️ this PR should not be merged before `feat/readonly`~~
____
Because `Cozy Connectors` is not a classic organization, user cannot
share it with others
So in this case `share` button is now hidden

fix: don't show `share` button on `Cozy Connectors` folder

---

CHANGELOG.md
src/services/cipher.service.ts

~~⚠️ this PR must not be merged on `feat/readonly` but on `master`. The target branch will be edited after `feat/readonly` merge~~
~~⚠️ this PR should not be merged before `feat/readonly`~~
____
On first `getAllDecrypted()` call, orgs may not have been synced yet
In this case `getAllDecrypted` would throw while getting all org ids
This error was non blocking as it was call on `GroupingsComponent` load
to check if Notes (cipher.type === 2) are in the list. As we don't
handle Notes this had no impact other than displaying an error in the
console
Now this case is handled correctly

fix: handle `getAllDecrypted` case where orgs are not synced yet

---

src/services/user.service.ts

After receiving a delete notification, then `deleteOrganization()` was
removing all organizations from local memory except the one that should
have been removed
Hopefully the impact was only on client side and would be canceled
after a fullSync

fix: delete the right local organization after a sync

---

src/services/cipher.service.ts

This hack is not needed anymore since the stack has been fixed with
following commits :
- cozy/cozy-stack@d77516d7b185188150f7b7103cd1fbcac7318ada
- cozy/cozy-stack@ee45a0f0b365e294fd030be2159f69a2dc61276e
- cozy/cozy-stack@99b992c2671af50ee73e2ec5c27f37692a4e3a91
This reverts b7a39083e76bc48365d85e060d302a60eddb19b6

refactor: remove hack when moving ciphers between and out of folders

---

src/services/sync.service.ts

After initializing a sharing, there is no garanty that organizations
are synced before ciphers on stack side
So we may receive a cipher from that organization before the
organization being accessible on the stack
So we wait a few seconds to ensure both events have been handled by the
stack

fix: wait a few seconds before syncing organization

---

package-lock.json
package.json

This retrieves a fix on `ConfirmTrustedRecipientsDialog` to correctly
display recipients' initials

feat: bump `cozy-sharing` version to 3.12.1

---

src/cozy/react/assets/store_android.svg
src/cozy/react/assets/store_ios.svg
src/cozy/react/components/browserIcons.js
src/cozy/react/locales/en.json
src/cozy/react/locales/fr.json

As CozyPass web was not ready to be used on mobile, we did not try the
CTA feature on those platforms
CozyPass web is not ready yet, but the `import` settings from CozyPass
mobile opens CozyPass web from the mobile. So we have to fix this issue
Generic `PhoneDevice` icon is used for both Android and iOS. This may
be replaced later with real stores icons when ready

fix: add translations and icons for "download" CTA on iOS and Android

---

src/app/vault/add-edit.component.html
src/locales/en/messages.json
src/locales/fr/messages.json

Notes were disabled to avoid confusion with Cozy Notes
We enable them again but named as Description
Related commit: 93e2d903f190b6c5570c4d5b134dac53184adbb8

feat: re-enable notes

---

manifest.webapp

This information can be used to open the native CozyPass app from
another Cozy app
Related PR: https://github.com/cozy/cozy-react-native/pull/65

feat: Add mobile info in manifest.webapp

---

package.json

In 8d36b7c5b9d3bfb4167b66a0c0469f36bed3636b the `build` script has been added using `yarn`
But the entire project uses `npm` so we want to homogenise the script

fix: Replace `yarn` by `npm` for `build` script

---

src/app/accounts/lock.component.html
src/app/accounts/login.component.html
src/app/accounts/two-factor.component.html
src/app/app.module.ts
src/app/vault/add-edit.component.html
src/app/vault/ciphers.component.html
src/app/vault/export.component.html
src/app/vault/folder-add-edit.component.html

Everything protected in the vault should be considered as sensible data that should not leak through browser's enhanced spellcheck
So we want to disable spellcheck on cozy-pass fields like password fields, names, urls, notes, address etc
This commit does not handle `send` feature fields as it deactivated and so we are not able to test it. But this should be considered if we implement it in the future
More info: https://www.otto-js.com/news/article/chrome-and-edge-enhanced-spellcheck-features-expose-pii-even-your-passwords
Related issue: bitwarden/desktop#842
___
This PR reflects https://github.com/cozy/cozy-keys-browser/pull/144

feat: Prevent spellcheck feature on form fields

---

src/cozy/wrappers/sharing/sharing.jsx
src/scss/cozy.scss

In #81 we added a badge on folders shared with another user that has not been valitated yet
When opening those folders, it was unclear for the user what to do next
So we want to add another badge on the Share button to indicates to the user that the next action is to go on the Share dialog which contains info about waiting users

feat: Add a badge to share button when users are waiting for validation

---

CHANGELOG.md
src/cozy/wrappers/confirm-trusted-users/confirm-trusted-users.component.ts

With previous implementation, if the `syncCompleted` happens before the first `renderReact()`, then the ConfirmTrustedUsers modal would be displayed even if there is no contact to confirm
In nominal scenario, the component would call `renderReact()` one to two times
The first render is always called and should be done with `showModal = false` and so the component should not be displayed
Then the component should receive the `syncCompleted` event, which should call `firstRenderReact()` that should check for users to be confirmed and then trigger `renderReact()` if necessary
But `showModal = true` was not conditioned to the presence of users to be confirmed. This is responsible of a race condition with the first `renderReact()` call
By moving `showModal = true` behind the condition, then …

fix: Prevent ConfirmTrustedUsers modal to be displayed on race condition

---

.travis.yml

We encountered a bug that prevents travis to trigger builds on tags
This makes the release builds impossible
To fix that we change the branches rules to target `release/x.y.z` branches instead of `x.y.z` tags
With this edit, we should be able to trigger release builds on tags if they are based on a `release/x.y.z` branch

fix: Make the CI target release branches

---

src/cozy/react/components/InstallationPage/components/HintStep.jsx
src/cozy/react/locales/en.json
src/cozy/react/locales/fr.json
src/cozy/wrappers/react-wrapper.jsx

When migrating `installation` components from React's router into
Angular's one, we lost the `Alerter` component that would react to
`Alerter.error()` calls
We want to re-introduce the `Alerter` in the react-wrapper component so
it would be accessible to all previously migrated components
Related commit: f66210c84581647929ca2641a6611aa2fe34dcef
Related commit: 0251b221637eba47a52512c605aefad3a3f2c021
This PR also improves the error message displayed when the Hint is the same as Password in the installation page

fix: Re-enable Alerter in react components

---

src/cozy/services/installation-guard.service.ts
src/cozy/wrappers/installation-page/installation-page.component.ts

In a previous commit we changed the bitwarden client's type from `webapp` to `web`
This had a side effect on onboarding that would not trigger migration from konnectors accounts to ciphers as this is prevented on `web` clients (because cozy-keys-lib is also flagged as a `web` client)
This is a requirement for setting `extension_installed` flag to `true`
The result was the onboarding screen to be always displayed when accessing cozy-pass-web
To fix this, the cozy-stack now has a new entry point `/settings/vault` that allows to enforce the migration from cozy-pass-web even if its client is a `web` one
We want to call this endpoint at the end of onboarding
Related PR: #109
Related PR: cozy/cozy-stack#4285
Related PR: cozy/cozy-stack#4303

[VO-99] fix: Call vault migration on onboarding's end

---

.travis.yml

In #112 we fixed a travis bug that prevented builds to be triggered by tags
Since then Travis fixed that issue and now we should revert previous commit in order to make CI work again

fix: Make the CI target tags

---

manifest.webapp

We need to add new permissions to web extension oauth token to support mespapiers features. We decided to now use the manifest permissions from cozy-pass-web for every cozy-pass app (web, browser, mobile).
What did I do : 
- Add missing permissions from here https://github.com/cozy/cozy-stack/blob/master/model/bitwarden/oauth.go#L19
- Add missing permissions for mespapiers features (GET io.cozy.files DELETE io.cozy.files)

feat: Add web extension permissions

---

.github/workflows/ci-cd.yml
package-lock.json
package.json

The variables `BUNDLEMON_PROJECT_ID` and `BUNDLEMON_PROJECT_APIKEY` are no longer required and must be deleted for new Bundlemon versions to work properly.

chore: Upgrade bundlemon to 3.1.0
